# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://erichall87.github.io/
baseurl: /sustain/
title: Eric Hall
author: Eric Hall
description: Personal blog and resume
avatar: profile.png
email: eric.hall87@email.com
github: erichall87 # username
twitter: erichall87
linkedin: Eric Hall


# needed for travis-ci build
exclude: [vendor]
